<?php

// This file was generated by running "composer dump-env prod"

return array (
  'APP_ENV' => 'prod',
  'SYMFONY_DOTENV_PATH' => './.env',
  'APP_DEBUG' => '0',
  'APP_SECRET' => '',
  'DATABASE_URL' => 'mysql://if0_39205323:fnSTppktYz3LEb@sql208.infinityfree.com:3306/if0_39205323_meetings_control?serverVersion=5.7&charset=utf8mb4',
  'MESSENGER_TRANSPORT_DSN' => 'doctrine://default?auto_setup=0',
  'MAILER_DSN' => 'smtp://af8dea2d205fa8:218b83b1424e30@sandbox.smtp.mailtrap.io:2525',
  'JWT_SECRET_KEY' => '%kernel.project_dir%/config/jwt/private.pem',
  'JWT_PUBLIC_KEY' => '%kernel.project_dir%/config/jwt/public.pem',
  'JWT_PASSPHRASE' => '252d81b80d6f18a506993271ca1ad6c286c3ddee52ae77fb47c1088c84895621',
  'MEETING_ROOM_PHOTOS_DIRECTORY' => '%kernel.project_dir%/public/uploads/meeting_rooms',
  'YANDEX_USERNAME' => 'maenkoivanov@yandex.ru',
  'YANDEX_APP_PASSWORD' => 'wixdnwcptlngnrep',
  'CORS_ALLOW_ORIGIN' => '^https://(meeting-frontend-cisf\.vercel\.app)$',
  'VAPID_PUBLIC_KEY' => 'BBceryB_Lo_6FOu8_jstUK5ExGze1esePCV8P8NwRbSCkOMeIm9xn23_7dTWM14M6YQx2VPEVX8yqcqtgezRppc',
  'VAPID_PRIVATE_KEY' => '_L0J44Y7bd2aIgpqPf8ElyHXKjlqEjsZhjpDeGRGYsY',
);
