<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWBe5s9X\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWBe5s9X/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerWBe5s9X.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerWBe5s9X\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerWBe5s9X\App_KernelProdContainer([
    'container.build_hash' => 'WBe5s9X',
    'container.build_id' => '0873be86',
    'container.build_time' => 1749650078,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWBe5s9X');
