<?php

namespace ContainerWBe5s9X;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Messenger_HandlerDescriptor_KmvZRTyService extends App_KernelProdContainer
{
    /*
     * Gets the private '.messenger.handler_descriptor.KmvZRTy' shared service.
     *
     * @return \Symfony\Component\Messenger\Handler\HandlerDescriptor
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container));

        if (isset($container->privates['.messenger.handler_descriptor.KmvZRTy'])) {
            return $container->privates['.messenger.handler_descriptor.KmvZRTy'];
        }
        $b = ($container->services['messenger.default_bus'] ?? $container->load('getMessenger_DefaultBusService'));

        if (isset($container->privates['.messenger.handler_descriptor.KmvZRTy'])) {
            return $container->privates['.messenger.handler_descriptor.KmvZRTy'];
        }

        return $container->privates['.messenger.handler_descriptor.KmvZRTy'] = new \Symfony\Component\Messenger\Handler\HandlerDescriptor(new \App\MessageHandler\SendNotificationMessageHandler($a, new \App\Service\NotificationService(new \Symfony\Component\Mailer\Mailer(($container->privates['mailer.transports'] ?? $container->load('getMailer_TransportsService')), $b, ($container->services['event_dispatcher'] ?? self::getEventDispatcherService($container))), $container->getEnv('VAPID_PUBLIC_KEY'), $container->getEnv('VAPID_PRIVATE_KEY'))), []);
    }
}
