<?php

namespace ContainerWBe5s9X;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEmployeeControllereditService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.gzyLs3m.App\Controller\EmployeeController::edit()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.gzyLs3m.App\\Controller\\EmployeeController::edit()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'employeeUpdateDTO' => ['privates', 'App\\DTO\\EmployeeUpdateDTO', 'getEmployeeUpdateDTOService', true],
        ], [
            'employeeUpdateDTO' => 'App\\DTO\\EmployeeUpdateDTO',
        ]))->withContext('App\\Controller\\EmployeeController::edit()', $container);
    }
}
