<?php

namespace ContainerWBe5s9X;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEventControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\EventController' shared autowired service.
     *
     * @return \App\Controller\EventController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\EventController'] = $instance = new \App\Controller\EventController(($container->privates['validator'] ?? self::getValidatorService($container)), new \App\Service\EventService(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)), ($container->privates['App\\Repository\\EventRepository'] ?? $container->load('getEventRepositoryService')), ($container->services['messenger.default_bus'] ?? $container->load('getMessenger_DefaultBusService'))));

        $instance->setContainer(($container->privates['.service_locator.ZyP9f7K'] ?? $container->load('get_ServiceLocator_ZyP9f7KService'))->withContext('App\\Controller\\EventController', $container));

        return $instance;
    }
}
