<?php

namespace ContainerWBe5s9X;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEmployeeControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\EmployeeController' shared autowired service.
     *
     * @return \App\Controller\EmployeeController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\EmployeeController'] = $instance = new \App\Controller\EmployeeController(new \App\Service\EmployeeService(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)), ($container->privates['security.user_password_hasher'] ?? $container->load('getSecurity_UserPasswordHasherService'))), ($container->privates['validator'] ?? self::getValidatorService($container)));

        $instance->setContainer(($container->privates['.service_locator.ZyP9f7K'] ?? $container->load('get_ServiceLocator_ZyP9f7KService'))->withContext('App\\Controller\\EmployeeController', $container));

        return $instance;
    }
}
