<?php

namespace ContainerWBe5s9X;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEventCreateDTOService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\DTO\EventCreateDTO' shared autowired service.
     *
     * @return \App\DTO\EventCreateDTO
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service "App\\DTO\\EventCreateDTO": argument "$name" of method "__construct()" is type-hinted "string", you should configure its value explicitly.');
    }
}
