<?php

namespace ContainerWBe5s9X;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMeetingRoomRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\MeetingRoomRepository' shared autowired service.
     *
     * @return \App\Repository\MeetingRoomRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\MeetingRoomRepository'] = new \App\Repository\MeetingRoomRepository(($container->services['doctrine'] ?? self::getDoctrineService($container)));
    }
}
