<?php

namespace ContainerWBe5s9X;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMeetingRoomControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\MeetingRoomController' shared autowired service.
     *
     * @return \App\Controller\MeetingRoomController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\MeetingRoomController'] = $instance = new \App\Controller\MeetingRoomController(new \App\Service\MeetingRoomService(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)), ($container->privates['App\\Repository\\MeetingRoomRepository'] ?? $container->load('getMeetingRoomRepositoryService')), ($container->privates['parameter_bag'] ??= new \Symfony\Component\DependencyInjection\ParameterBag\ContainerBag($container))), ($container->privates['validator'] ?? self::getValidatorService($container)));

        $instance->setContainer(($container->privates['.service_locator.ZyP9f7K'] ?? $container->load('get_ServiceLocator_ZyP9f7KService'))->withContext('App\\Controller\\MeetingRoomController', $container));

        return $instance;
    }
}
