<?php

namespace ContainerWBe5s9X;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOfficeRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\OfficeRepository' shared autowired service.
     *
     * @return \App\Repository\OfficeRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\OfficeRepository'] = new \App\Repository\OfficeRepository(($container->services['doctrine'] ?? self::getDoctrineService($container)));
    }
}
