<?php

namespace ContainerWBe5s9X;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOrganizationControlleraddService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.5Bq374f.App\Controller\OrganizationController::add()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.5Bq374f.App\\Controller\\OrganizationController::add()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'organizationCreateDTO' => ['privates', 'App\\DTO\\OrganizationCreateDTO', NULL, 'Cannot autowire service "App\\DTO\\OrganizationCreateDTO": argument "$name" of method "__construct()" is type-hinted "string", you should configure its value explicitly.'],
        ], [
            'organizationCreateDTO' => 'App\\DTO\\OrganizationCreateDTO',
        ]))->withContext('App\\Controller\\OrganizationController::add()', $container);
    }
}
