<?php

namespace ContainerWBe5s9X;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOfficeControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\OfficeController' shared autowired service.
     *
     * @return \App\Controller\OfficeController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\OfficeController'] = $instance = new \App\Controller\OfficeController(($container->privates['validator'] ?? self::getValidatorService($container)), new \App\Service\OfficeService(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container))));

        $instance->setContainer(($container->privates['.service_locator.ZyP9f7K'] ?? $container->load('get_ServiceLocator_ZyP9f7KService'))->withContext('App\\Controller\\OfficeController', $container));

        return $instance;
    }
}
