<?php

namespace ContainerWBe5s9X;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOrganizationUpdateDTOService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\DTO\OrganizationUpdateDTO' shared autowired service.
     *
     * @return \App\DTO\OrganizationUpdateDTO
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\DTO\\OrganizationUpdateDTO'] = new \App\DTO\OrganizationUpdateDTO();
    }
}
