<?php

namespace ContainerSQWl3be;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_TiqkxjBService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.tiqkxjB' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.tiqkxjB'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\EmployeeController::register' => ['privates', '.service_locator.ldhUTFM.App\\Controller\\EmployeeController::register()', 'getEmployeeControllerregisterService', true],
            'App\\Controller\\EmployeeController::edit' => ['privates', '.service_locator.gzyLs3m.App\\Controller\\EmployeeController::edit()', 'getEmployeeControllereditService', true],
            'App\\Controller\\EventController::add' => ['privates', '.service_locator.o.yXwmU.App\\Controller\\EventController::add()', 'getEventControlleraddService', true],
            'App\\Controller\\EventController::edit' => ['privates', '.service_locator.bHaA4xz.App\\Controller\\EventController::edit()', 'getEventControllereditService', true],
            'App\\Controller\\MeetingRoomController::add' => ['privates', '.service_locator.7rsb3NN.App\\Controller\\MeetingRoomController::add()', 'getMeetingRoomControlleraddService', true],
            'App\\Controller\\MeetingRoomController::edit' => ['privates', '.service_locator._kKDSn4.App\\Controller\\MeetingRoomController::edit()', 'getMeetingRoomControllereditService', true],
            'App\\Controller\\OfficeController::add' => ['privates', '.service_locator.dojY8g_.App\\Controller\\OfficeController::add()', 'getOfficeControlleraddService', true],
            'App\\Controller\\OfficeController::edit' => ['privates', '.service_locator.wPIyTOX.App\\Controller\\OfficeController::edit()', 'getOfficeControllereditService', true],
            'App\\Controller\\OrganizationController::add' => ['privates', '.service_locator.5Bq374f.App\\Controller\\OrganizationController::add()', 'getOrganizationControlleraddService', true],
            'App\\Controller\\OrganizationController::edit' => ['privates', '.service_locator.P2BD4um.App\\Controller\\OrganizationController::edit()', 'getOrganizationControllereditService', true],
            'App\\Controller\\PushSubscriptionController::subscribe' => ['privates', '.service_locator.Kq27LHM.App\\Controller\\PushSubscriptionController::subscribe()', 'getPushSubscriptionControllersubscribeService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\EmployeeController:register' => ['privates', '.service_locator.ldhUTFM.App\\Controller\\EmployeeController::register()', 'getEmployeeControllerregisterService', true],
            'App\\Controller\\EmployeeController:edit' => ['privates', '.service_locator.gzyLs3m.App\\Controller\\EmployeeController::edit()', 'getEmployeeControllereditService', true],
            'App\\Controller\\EventController:add' => ['privates', '.service_locator.o.yXwmU.App\\Controller\\EventController::add()', 'getEventControlleraddService', true],
            'App\\Controller\\EventController:edit' => ['privates', '.service_locator.bHaA4xz.App\\Controller\\EventController::edit()', 'getEventControllereditService', true],
            'App\\Controller\\MeetingRoomController:add' => ['privates', '.service_locator.7rsb3NN.App\\Controller\\MeetingRoomController::add()', 'getMeetingRoomControlleraddService', true],
            'App\\Controller\\MeetingRoomController:edit' => ['privates', '.service_locator._kKDSn4.App\\Controller\\MeetingRoomController::edit()', 'getMeetingRoomControllereditService', true],
            'App\\Controller\\OfficeController:add' => ['privates', '.service_locator.dojY8g_.App\\Controller\\OfficeController::add()', 'getOfficeControlleraddService', true],
            'App\\Controller\\OfficeController:edit' => ['privates', '.service_locator.wPIyTOX.App\\Controller\\OfficeController::edit()', 'getOfficeControllereditService', true],
            'App\\Controller\\OrganizationController:add' => ['privates', '.service_locator.5Bq374f.App\\Controller\\OrganizationController::add()', 'getOrganizationControlleraddService', true],
            'App\\Controller\\OrganizationController:edit' => ['privates', '.service_locator.P2BD4um.App\\Controller\\OrganizationController::edit()', 'getOrganizationControllereditService', true],
            'App\\Controller\\PushSubscriptionController:subscribe' => ['privates', '.service_locator.Kq27LHM.App\\Controller\\PushSubscriptionController::subscribe()', 'getPushSubscriptionControllersubscribeService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Controller\\EmployeeController::register' => '?',
            'App\\Controller\\EmployeeController::edit' => '?',
            'App\\Controller\\EventController::add' => '?',
            'App\\Controller\\EventController::edit' => '?',
            'App\\Controller\\MeetingRoomController::add' => '?',
            'App\\Controller\\MeetingRoomController::edit' => '?',
            'App\\Controller\\OfficeController::add' => '?',
            'App\\Controller\\OfficeController::edit' => '?',
            'App\\Controller\\OrganizationController::add' => '?',
            'App\\Controller\\OrganizationController::edit' => '?',
            'App\\Controller\\PushSubscriptionController::subscribe' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Controller\\EmployeeController:register' => '?',
            'App\\Controller\\EmployeeController:edit' => '?',
            'App\\Controller\\EventController:add' => '?',
            'App\\Controller\\EventController:edit' => '?',
            'App\\Controller\\MeetingRoomController:add' => '?',
            'App\\Controller\\MeetingRoomController:edit' => '?',
            'App\\Controller\\OfficeController:add' => '?',
            'App\\Controller\\OfficeController:edit' => '?',
            'App\\Controller\\OrganizationController:add' => '?',
            'App\\Controller\\OrganizationController:edit' => '?',
            'App\\Controller\\PushSubscriptionController:subscribe' => '?',
        ]);
    }
}
