<?php

namespace ContainerSQWl3be;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEmployeeControllerregisterService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ldhUTFM.App\Controller\EmployeeController::register()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ldhUTFM.App\\Controller\\EmployeeController::register()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'employeeCreateDTO' => ['privates', 'App\\DTO\\EmployeeCreateDTO', NULL, 'Cannot autowire service "App\\DTO\\EmployeeCreateDTO": argument "$organizationId" of method "__construct()" is type-hinted "int", you should configure its value explicitly.'],
        ], [
            'employeeCreateDTO' => 'App\\DTO\\EmployeeCreateDTO',
        ]))->withContext('App\\Controller\\EmployeeController::register()', $container);
    }
}
