<?php

namespace ContainerSQWl3be;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEventSynchronizationListenerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\EventListener\EventSynchronizationListener' shared autowired service.
     *
     * @return \App\EventListener\EventSynchronizationListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'EventListener'.\DIRECTORY_SEPARATOR.'EventSynchronizationListener.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'YandexCalendarService.php';

        $a = ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container));

        if (isset($container->privates['App\\EventListener\\EventSynchronizationListener'])) {
            return $container->privates['App\\EventListener\\EventSynchronizationListener'];
        }

        return $container->privates['App\\EventListener\\EventSynchronizationListener'] = new \App\EventListener\EventSynchronizationListener(new \App\Service\YandexCalendarService($container->getEnv('YANDEX_USERNAME'), $container->getEnv('YANDEX_APP_PASSWORD'), $a));
    }
}
