<?php

namespace ContainerSQWl3be;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMeetingRoomControlleraddService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.7rsb3NN.App\Controller\MeetingRoomController::add()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.7rsb3NN.App\\Controller\\MeetingRoomController::add()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'meetingRoomCreateDTO' => ['privates', 'App\\DTO\\MeetingRoomCreateDTO', NULL, 'Cannot autowire service "App\\DTO\\MeetingRoomCreateDTO": argument "$name" of method "__construct()" is type-hinted "string", you should configure its value explicitly.'],
        ], [
            'meetingRoomCreateDTO' => 'App\\DTO\\MeetingRoomCreateDTO',
        ]))->withContext('App\\Controller\\MeetingRoomController::add()', $container);
    }
}
