<?php

namespace ContainerSQWl3be;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOrganizationControllereditService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.P2BD4um.App\Controller\OrganizationController::edit()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.P2BD4um.App\\Controller\\OrganizationController::edit()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'organizationUpdateDTO' => ['privates', 'App\\DTO\\OrganizationUpdateDTO', 'getOrganizationUpdateDTOService', true],
        ], [
            'organizationUpdateDTO' => 'App\\DTO\\OrganizationUpdateDTO',
        ]))->withContext('App\\Controller\\OrganizationController::edit()', $container);
    }
}
