<?php

namespace ContainerSQWl3be;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOrganizationStatusListenerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\EventListener\OrganizationStatusListener' shared autowired service.
     *
     * @return \App\EventListener\OrganizationStatusListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'EventListener'.\DIRECTORY_SEPARATOR.'OrganizationStatusListener.php';

        $a = ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container));

        if (isset($container->privates['App\\EventListener\\OrganizationStatusListener'])) {
            return $container->privates['App\\EventListener\\OrganizationStatusListener'];
        }

        return $container->privates['App\\EventListener\\OrganizationStatusListener'] = new \App\EventListener\OrganizationStatusListener($a);
    }
}
