<?php

namespace ContainerSQWl3be;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOfficeControlleraddService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.dojY8g_.App\Controller\OfficeController::add()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.dojY8g_.App\\Controller\\OfficeController::add()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'officeCreateDTO' => ['privates', 'App\\DTO\\OfficeCreateDTO', NULL, 'Cannot autowire service "App\\DTO\\OfficeCreateDTO": argument "$name" of method "__construct()" is type-hinted "string", you should configure its value explicitly.'],
        ], [
            'officeCreateDTO' => 'App\\DTO\\OfficeCreateDTO',
        ]))->withContext('App\\Controller\\OfficeController::add()', $container);
    }
}
