<?php

namespace ContainerSQWl3be;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOfficeControllereditService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.wPIyTOX.App\Controller\OfficeController::edit()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.wPIyTOX.App\\Controller\\OfficeController::edit()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'officeUpdateDTO' => ['privates', 'App\\DTO\\OfficeUpdateDTO', 'getOfficeUpdateDTOService', true],
        ], [
            'officeUpdateDTO' => 'App\\DTO\\OfficeUpdateDTO',
        ]))->withContext('App\\Controller\\OfficeController::edit()', $container);
    }
}
