<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSQWl3be\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSQWl3be/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerSQWl3be.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerSQWl3be\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerSQWl3be\App_KernelDevDebugContainer([
    'container.build_hash' => 'SQWl3be',
    'container.build_id' => '58a5cdf0',
    'container.build_time' => 1744634701,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSQWl3be');
