<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class MeetingRoom extends \App\Entity\MeetingRoom implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'access' => [parent::class, 'access', null],
        "\0".parent::class."\0".'calendar_code' => [parent::class, 'calendar_code', null],
        "\0".parent::class."\0".'description' => [parent::class, 'description', null],
        "\0".parent::class."\0".'employees' => [parent::class, 'employees', null],
        "\0".parent::class."\0".'events' => [parent::class, 'events', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'is_public' => [parent::class, 'is_public', null],
        "\0".parent::class."\0".'name' => [parent::class, 'name', null],
        "\0".parent::class."\0".'office' => [parent::class, 'office', null],
        "\0".parent::class."\0".'photo_path' => [parent::class, 'photo_path', null],
        "\0".parent::class."\0".'size' => [parent::class, 'size', null],
        "\0".parent::class."\0".'status' => [parent::class, 'status', null],
        'access' => [parent::class, 'access', null],
        'calendar_code' => [parent::class, 'calendar_code', null],
        'description' => [parent::class, 'description', null],
        'employees' => [parent::class, 'employees', null],
        'events' => [parent::class, 'events', null],
        'id' => [parent::class, 'id', null],
        'is_public' => [parent::class, 'is_public', null],
        'name' => [parent::class, 'name', null],
        'office' => [parent::class, 'office', null],
        'photo_path' => [parent::class, 'photo_path', null],
        'size' => [parent::class, 'size', null],
        'status' => [parent::class, 'status', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
