<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Employee extends \App\Entity\Employee implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'email' => [parent::class, 'email', null],
        "\0".parent::class."\0".'events' => [parent::class, 'events', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'name' => [parent::class, 'name', null],
        "\0".parent::class."\0".'organization' => [parent::class, 'organization', null],
        "\0".parent::class."\0".'password' => [parent::class, 'password', null],
        "\0".parent::class."\0".'patronymic' => [parent::class, 'patronymic', null],
        "\0".parent::class."\0".'pushSubscriptions' => [parent::class, 'pushSubscriptions', null],
        "\0".parent::class."\0".'roles' => [parent::class, 'roles', null],
        "\0".parent::class."\0".'surname' => [parent::class, 'surname', null],
        'email' => [parent::class, 'email', null],
        'events' => [parent::class, 'events', null],
        'id' => [parent::class, 'id', null],
        'name' => [parent::class, 'name', null],
        'organization' => [parent::class, 'organization', null],
        'password' => [parent::class, 'password', null],
        'patronymic' => [parent::class, 'patronymic', null],
        'pushSubscriptions' => [parent::class, 'pushSubscriptions', null],
        'roles' => [parent::class, 'roles', null],
        'surname' => [parent::class, 'surname', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
